
application:
  db:
    host: localhost
    port: 6432
    name: highload_architect
    schema: demo
    username: postgres
    password: Passw00rd!
    replicas: localhost:6433,localhost:6434

spring:
  liquibase.contexts: init_data

#logging:
#  level:
#    org.springframework.r2dbc: trace
server:
  port: 8090